### ISSUE TITLE
Do Delete Object 404 will be returned

### ISSUE THREAD

**Issue by masaakikunsan** [cosmicjs/rest-api-docs#2]
https://cosmicjs.github.io/rest-api-docs/?bash#delete-object
If you do an example request on the link above it will return 404. Is this a bug?

**Comment by masaakikunsan** [comment]
You can delete by hitting the API Endpoint written in bash with axios.

**Comment by tonyspiro** [comment]
Are you using the proper `bucket_slug` and `object_slug`?

**Comment by masaakikunsan** [comment]
Yes!
Because axios uses exactly the same bucket_slug and object_slug.
If bucket_slug and object_slug are incorrect it is strange that you can delete it with axios.

**Comment by tonyspiro** [comment]
Those are variables and you will need to use your own real `bucket_slug` and `object_slug` values.
